// productos.js
export const productos = [
    { nombre: "Osito de invierno - GAP", precio: 26000, categoria: "ropa", img: "../img/tienda/ropa-calzado/osito-gap.webp", publicado: "Martina" },
    { nombre: "Osito de invierno - H&M", precio: 23000, categoria: "ropa", img: "../img/tienda/ropa-calzado/osito-hm.webp", publicado: "Martina" },
    { nombre: "Pack 2 Ositos - Carter's", precio: 29000, categoria: "ropa", img: "../img/tienda/ropa-calzado/pack-ositos.webp", publicado: "Martina" },
    { nombre: "Pack 3 Bodies - Cheeky", precio: 17000, categoria: "ropa", img: "../img/tienda/ropa-calzado/pack3-bodies.webp", publicado: "Valentina" },
    { nombre: "Pack 4 Bodies animales - Buditas", precio: 14000, categoria: "ropa", img: "../img/tienda/ropa-calzado/pack4-bodies.webp", publicado: "Valentina" },
    { nombre: "Body flores - Little Akiabara", precio: 12000, categoria: "ropa", img: "../img/tienda/ropa-calzado/bodyflor-la.webp", publicado: "Julieta" },
    { nombre: "Enterito flores - Little Akiabara", precio: 17000, categoria: "ropa", img: "../img/tienda/ropa-calzado/enterito-la.webp", publicado: "Martina" },
    { nombre: "Almohadón de lactancia - Mamas and Papas", precio: 45000, categoria: "lactancia", img: "../img/tienda/lactancia/almohadon.jpg", publicado: "Malena" },
    { nombre: "Almohadón para amamantar", precio: 20000, categoria: "lactancia", img: "../img/tienda/lactancia/almohadon-amamantar.jpg", publicado: "Raquel" },
    { nombre: "Mochila porta bebé 4004 - Love", precio: 27000, categoria: "porteo", img: "../img/tienda/porteo/mochila-love.webp", publicado: "Mora" },
    { nombre: "Mochila porta bebé Gera - Duck", precio: 25000, categoria: "porteo", img: "../img/tienda/porteo/mochila-duck1.jpg", publicado: "Virginia" },
    { nombre: "Huevito Kiev 2023 - Carestino", precio: 57000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/huevito-kiev.jpg", publicado: "Rocío" },
    { nombre: "Funda de huevito - Skip Hop", precio: 34000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/funda-huevito.jpg", publicado: "Agustina" },
    { nombre: "Cochecito Kolcraft 2019 - Cloud", precio: 70000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/cochecito-cloud.jpg", publicado: "Jimena" },
    { nombre: "Cochecito Elite Premium 2023 - Mega Baby", precio: 203000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/cochecito-megababy.jpg", publicado: "Macarena" },
    { nombre: "Cochecito Aston - Premium Baby", precio: 205000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/coche-aston.jpg", publicado: "Rosario" },
    { nombre: "Patineta para cochecito - Britax", precio: 57000, categoria: "cochecitos", img: "../img/tienda/cochecitos-accesorios/patineta.jpg", publicado: "Paloma" },
    { nombre: "Cuna colecho (sin uso) melamina", precio: 100000, categoria: "cunas", img: "../img/tienda/cunas/cuna-melamina.jpg", publicado: "Camila" },
    { nombre: "Cuna colecho pino laqueada", precio: 92000, categoria: "cunas", img: "../img/tienda/cunas/cuna-pino.jpg", publicado: "Josefina" },
    { nombre: "Cuna Charriot Paraiso escandinava", precio: 102000, categoria: "cunas", img: "../img/tienda/cunas/cuna-escandinava.jpg", publicado: "Victoria" },
    { nombre: "Cuna colecho madera maciza", precio: 86000, categoria: "cunas", img: "../img/tienda/cunas/cuna-maciza.jpg", publicado: "Milagros" },
    { nombre: "Practicuna Breeze Go - 4Moms", precio: 85000, categoria: "cunas", img: "../img/tienda/cunas/practicuna-4moms.jpg", publicado: "Florencia" },
    { nombre: "Practicuna Pack and Play - Graco", precio: 69000, categoria: "cunas", img: "../img/tienda/cunas/practicuna-graco.jpg", publicado: "Abril" },
    { nombre: "Practicuna Illusion - Joie", precio: 92000, categoria: "cunas", img: "../img/tienda/cunas/cuna-joie.jpg", publicado: "Katherine" },
    { nombre: "Silla mecedora - Bebesit", precio: 51000, categoria: "mecedoras", img: "../img/tienda/mecedoras/mecedora-fisher.jpg", publicado: "Isabella" },
    { nombre: "Mecedora - Felcraft", precio: 39000, categoria: "mecedoras", img: "../img/tienda/mecedoras/mecedora-fel.jpg", publicado: "María" },
    { nombre: "Silla mecedora - Baby Innovation", precio: 45000, categoria: "mecedoras", img: "../img/tienda/mecedoras/silla-baby.jpg", publicado: "Antonella" },
    { nombre: "Mecedora - Fisher Price", precio: 72000, categoria: "mecedoras", img: "../img/tienda/mecedoras/silla-bebesit.jpg", publicado: "Daniela" },
    { nombre: "Móvil cunero (sin uso)", precio: 29000, categoria: "diversion", img: "../img/tienda/diversion/movil.jpg", publicado: "Ornella" },
    { nombre: "Play center - B Kids", precio: 11000, categoria: "diversion", img: "../img/tienda/diversion/playcenter.jpg", publicado: "Alicia" },
    { nombre: "Manta didáctica 3 en 1 - Ok Baby", precio: 31000, categoria: "diversion", img: "../img/tienda/diversion/manta.jpg", publicado: "Bárbara" },
    { nombre: "Gimnasio - Fisher Price", precio: 33000, categoria: "diversion", img: "../img/tienda/diversion/gimnasio.webp", publicado: "Candela" },
    { nombre: "Pelotero - Fisher Price", precio: 39000, categoria: "diversion", img: "../img/tienda/diversion/pelotero-fisher.jpg", publicado: "Emilia" },
    { nombre: "Pelotero 3 en 1- Felcraft", precio: 45000, categoria: "diversion", img: "../img/tienda/diversion/pelotero-fel.jpg", publicado: "Giselle" },
    { nombre: "Silla de comer 2 en 1 - Baby Pops", precio: 65000, categoria: "sillitas", img: "../img/tienda/sillitas de comer/silla-baby.jpg", publicado: "Lucero" },
    { nombre: "Silla de comer Booster - Glee", precio: 25000, categoria: "sillitas", img: "../img/tienda/sillitas de comer/silla-glee.jpg", publicado: "Ludmila" }
];
